In [1]:
from src.extraction import get_genres, fetch_wars_data, fetch_full_history
from src.cleaning import clean_movies_data, clean_wars_data
import pandas as pd

In [2]:
genres_list = get_genres()
genre_dict = {g['id']: g['name'] for g in genres_list}
genres_list

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [3]:
#raw_movies_list = fetch_full_history(1930, 2024)

In [4]:
#df_movies_raw = pd.json_normalize(raw_movies_list)

In [5]:
#df_movies_raw.to_pickle("data/raw/movies_raw.pkl")

In [6]:
df_movies_raw = pd.read_pickle("data/raw/movies_raw.pkl")
df_movies_raw.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,None,[35],277845,de,Lumpenball,,8.5754,None,1930-08-18,Lumpenball,False,0.0,0
1,False,/gzcfhMFuoryamZ2hOkICFMc6oGk.jpg,"[12, 80, 10749]",104439,en,Raffles,A distinguished English gentleman has a secret...,8.4912,/mOeP2d3JO1Q8bLgphb9zyEM3spG.jpg,1930-07-11,Raffles,False,6.1,15
2,False,None,[16],165988,en,Mexico,Oswald's rooster fights Pete's rooster in a br...,8.6946,None,1930-11-16,Mexico,False,4.0,1
3,False,/KuBmDhZemKuSGozyRHjynCboES.jpg,[35],387963,en,Lightnin',Lightnin' and Mary Jones are co-owners of a ho...,7.6463,/wYdSij08by4TudnmOEG6CoAUU7r.jpg,1930-11-28,Lightnin',False,3.7,3
4,False,None,[],1079538,en,Olimpia,"Spanish version of the MGM romance, His Glorio...",8.3005,/9FAfMmkj8Ul32eGqTUbfmyb7eHo.jpg,1930-10-10,Olimpia,False,0.0,0

In [7]:
df_movies_final = clean_movies_data(df_movies_raw, genre_dict)
df_movies_final.head()

        id       title release_date    genre_ids  year main_genre  decade
0   277845  Lumpenball   1930-08-18           35  1930     Comedy    1930
1   104439     Raffles   1930-07-11  12,80,10749  1930  Adventure    1930
2   165988      Mexico   1930-11-16           16  1930  Animation    1930
3   387963   Lightnin'   1930-11-28           35  1930     Comedy    1930
4  1067244   Tom Mixup   1930-02-01     16,35,37  1930  Animation    1930

In [8]:
df_movies_final['decade'].value_counts().sort_index()

decade
1930    1472
1940    1604
1950    1502
1960    1442
1970    1607
1980    1767
1990    1994
2000    2159
2010    2164
2020    1144
Name: count, dtype: int64

In [9]:
movie_counts = (df_movies_final).groupby(['decade', 'main_genre'])['id'].size().reset_index(name='num_movies')
movie_counts.head()

   decade main_genre  num_movies
0    1930     Action          43
1    1930  Adventure          57
2    1930  Animation          81
3    1930     Comedy         328
4    1930      Crime         100

In [10]:
df_war_movies = df_movies_final[df_movies_final['main_genre']== 'War']

war_movies_by_decade = (df_war_movies.groupby('decade')['id'].size().reset_index(name="num_war_movies"))
war_movies_by_decade

   decade  num_war_movies
0    1930              21
1    1940              73
2    1950              38
3    1960              43
4    1970              35
5    1980              23
6    1990              17
7    2000              26
8    2010              22
9    2020              12

Guerras (Wikipedia)

In [11]:
df_wars_raw = fetch_wars_data()
df_wars_raw.head()

,started_year,ended_year,conflict_name,source_page
0,1900,1905,1900–1905 phase of the Mat Salleh Rebellion,https://en.wikipedia.org/wiki/List_of_wars:_19...
1,1900,1920,Somaliland campaign,https://en.wikipedia.org/wiki/List_of_wars:_19...
2,1900,1900,War of the Golden Stool,https://en.wikipedia.org/wiki/List_of_wars:_19...
3,1900,1905,Zande resistance [ 2 ],https://en.wikipedia.org/wiki/List_of_wars:_19...
4,1900,1902,Muhammad Umar Khan's rebellion [ 3 ],https://en.wikipedia.org/wiki/List_of_wars:_19...

In [12]:
df_wars_raw.shape

(1144, 4)

In [13]:
df_wars_final = clean_wars_data(df_wars_raw, min_year=1930, max_year=2024)
df_wars_final.head()

,started_year,ended_year,conflict_name,source_page,start_year,end_year,decade
0,1930,1930,Shinwari rebellion,https://en.wikipedia.org/wiki/List_of_wars:_19...,1930,1930,1930
1,1930,1930,1930 Kurdish rebellions [ 83 ],https://en.wikipedia.org/wiki/List_of_wars:_19...,1930,1930,1930
2,1930,1931,Afridi Redshirt Rebellion,https://en.wikipedia.org/wiki/List_of_wars:_19...,1930,1931,1930
3,1930,1931,Uprising of the Nghệ-Tĩnh Soviets,https://en.wikipedia.org/wiki/List_of_wars:_19...,1930,1931,1930
4,1930,1930,Hnov uprising [ ru ],https://en.wikipedia.org/wiki/List_of_wars:_19...,1930,1930,1930

In [14]:
df_wars_final['decade'].value_counts().sort_index()

decade
1930    98
1940    73
1950    58
1960    82
1970    64
1980    48
1990    66
2000    58
2010    62
2020    44
Name: count, dtype: Int64

In [15]:
def get_conflict_intensity_by_decade(df, min_year=1930, max_year=2024):
    decade_list = []

    for i in range(len(df)):
        start = df.loc[i, "start_year"]
        end = df.loc[i, "end_year"]

        if pd.isna(end):
            end = max_year

        start = int(start)
        end = int(end)

        for year in range(start, end + 1):
            if min_year <= year <= max_year:
                decade = (year // 10) * 10
                decade_list.append(decade)

    df_intensity = (
        pd.Series(decade_list)
        .value_counts()
        .sort_index()
        .reset_index()
    )

    df_intensity.columns = ["decade", "intensity"]
    df_intensity["intensity"] = df_intensity["intensity"].astype(int)

    return df_intensity

In [16]:
df_intensity = get_conflict_intensity_by_decade(df_wars_final)
df_intensity

   decade  intensity
0    1930        158
1    1940        217
2    1950        303
3    1960        421
4    1970        519
5    1980        596
6    1990        613
7    2000        628
8    2010        788
9    2020        447

MERGE

In [17]:
h1 = pd.merge(war_movies_by_decade, df_intensity, on='decade', how='left')
h1["intensity"] = h1["intensity"].fillna(0).astype(int)

h1.sort_values('decade')

   decade  num_war_movies  intensity
0    1930              21        158
1    1940              73        217
2    1950              38        303
3    1960              43        421
4    1970              35        519
5    1980              23        596
6    1990              17        613
7    2000              26        628
8    2010              22        788
9    2020              12        447

In [18]:
df_intensity_h2 = df_intensity.copy()
df_intensity_h2["decade_plus_one"] = df_intensity_h2['decade'] + 10

In [19]:
h2 = pd.merge(war_movies_by_decade, df_intensity_h2[["decade_plus_one", "intensity"]], left_on='decade', right_on="decade_plus_one", how="left").drop(columns=["decade_plus_one"])

In [20]:
h2["intensity"] = h2["intensity"].fillna(0).astype(int)

In [21]:
h2 = h2.rename(columns={"intensity" : "intensity_prev_decade"})

In [26]:
final_compare = pd.merge(
    h1,
    h2[["decade", "intensity_prev_decade"]],
    on="decade",
    how="left"
)

final_compare = final_compare.sort_values("decade")
final_compare

   decade  num_war_movies  intensity  intensity_prev_decade
0    1930              21        158                      0
1    1940              73        217                    158
2    1950              38        303                    217
3    1960              43        421                    303
4    1970              35        519                    421
5    1980              23        596                    519
6    1990              17        613                    596
7    2000              26        628                    613
8    2010              22        788                    628
9    2020              12        447                    788